Udemy Set 1

1. Session Controls
    - defines how long users remains active 

  Reauthenticaiton Freq
    - reduce session exposure time
    - req users to confirm identity again

  Org Policy constraints
    - centralized mngmt of resources w/in scope o policy

2. Service account key
  - a bot that interacts across GC services to lessen user intervention

  Audit logs
    - records admin activties and access including API keys

  Logs Explorer
    - allows users to sort, search., and anlayze log dat across GC services

3. Org policy 
  - centralized cloud governance and compliance

  CMEK  
    - cryption keys that are created, owned, and managed by customers, giving them control over the encryption and decryption of their data at rest in Google Clou

  constraints
    - limit control of resources

  policy binding
    - enforce define restrictions across resources

  deny policies
    -

4. Google Cloud Directory Sync: A tool used for synchronizing data from Active Directory or LDAP servers to Google Cloud Identity or G Suite accounts, typically for user and group management.

LDAP search rules: Search rules defined within an LDAP system to filter and retrieve specific records based on the defined attributes or conditions from a directory service.

One-way synchronization: A data sync process where information is transferred from one source (e.g., Active Directory) to another (e.g., Cloud IAM) but not in the reverse direction, thus only updating the target system.


28.Admin Activity audit logs: Logs that record operations that modify the configuration or metadata of resources. Essential for monitoring and securing administrative actions.

  Data Access audit logs: Logs that track API calls that create, modify, or read user-provided data. Vital for assessing who accesses sensitive data and how.

  System Event audit logs: Logs that record Google Cloud system events, which are automatically produced by Google services, rather than driven by direct user actions.

  Cloud Load Balancing logs: Logs generated by Google Cloud Load Balancing, providing insights into the requests made to an application rather than access to the configuration data.

  Compute Engine operation logs: Logs that detail operations performed on Compute Engine resources, relevant to infrastructure activities but not directly to sensitive data access.


